# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='teachers.Teacher'),
        ),
    ]
