# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(null=True, to='teachers.Teacher'),
        ),
    ]
