# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170620_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='teachers.Teacher'),
        ),
    ]
