# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('PHY', 'Physics')], default='CS', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('TE', 'teacher')], default='TE', max_length=10),
        ),
    ]
