# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20171220_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('UN', 'undefined'), ('CS', 'Computer Science'), ('PHY', 'Physics')], default='UN', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('UN', 'undefined'), ('TE', 'teacher')], default='UN', max_length=10),
        ),
    ]
