# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=64)),
                ('file', models.FileField(blank=True, null=True, upload_to='text/%Y/%m/%d')),
            ],
        ),
    ]
