# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-23 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0004_auto_20171222_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UNDEFINED', max_length=64)),
                ('level', models.IntegerField(choices=[(0, 'normal'), (1, 'middle'), (2, 'important')], default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('comment', models.TextField(null=True)),
                ('begin_time', models.TimeField(null=True)),
                ('finish_time', models.TimeField(null=True)),
                ('close_time', models.TimeField(null=True)),
                ('executors', models.ManyToManyField(blank=True, null=True, related_name='executors', to='teachers.Teacher')),
                ('managers', models.ManyToManyField(blank=True, null=True, related_name='managers', to='teachers.Teacher')),
            ],
        ),
    ]
