# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(blank=True, null=True, related_name='executorTasks', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='task',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, related_name='managerTasks', to='teachers.Teacher'),
        ),
    ]
