# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-29 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20171228_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_time',
            field=models.DateField(null=True),
        ),
    ]
