# Generated by Django 2.0.1 on 2018-01-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20171229_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='executorTasks', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='task',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managerTasks', to='teachers.Teacher'),
        ),
    ]
