# Generated by Django 2.0.1 on 2018-01-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180115_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
