# Generated by Django 2.0.1 on 2018-01-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180117_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='begin_time',
            field=models.DateField(null=True),
        ),
    ]
