# Generated by Django 2.0.1 on 2018-01-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20180117_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'executing'), (1, 'checking'), (2, 'finished')], default=0),
        ),
    ]
