# Generated by Django 2.0.1 on 2018-01-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20180117_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_time',
            field=models.DateField(null=True),
        ),
    ]
