# Generated by Django 2.0.1 on 2018-03-27 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0)),
                ('comment', models.TextField(default='no comment')),
                ('valid', models.BooleanField(default=False)),
                ('check_list', models.CharField(max_length=5, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
