# Generated by Django 2.0.1 on 2018-04-04 02:40

from django.db import migrations, models
import helper.models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_account_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=helper.models.set_path),
        ),
    ]
