# Generated by Django 2.0.1 on 2018-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_account_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='check_list',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
